project:
  type: website
  resources:
    - google46774d30bc5fcf21.html

website:
  title: "Adam Maghout"
  favicon: images/icon.png
  navbar:
    left:
      - href: about-me.qmd
        text: About me
      - href: projects.qmd
        text: Projects
      - href: CV.qmd
        text: CV
      - href: skills.qmd
        text: Skills
  page-footer:
    center: "Â© <script>document.write(new Date().getFullYear());</script> Adam Maghout"
  include-in-header: _includes/search-console.html
        
format:
  html:
    theme: lux
    css: styles.css

    toc: true

